import mapExists from "@xtjs/lib/mapExists";
import { DateTime, FixedOffsetZone } from "luxon";
import { Comment, Post, crawlHn, itemToPostOrComment } from "./main";

test(
  "crawlHn",
  async () => {
    const posts = Array<Post>();
    const comments = Array<Comment>();
    const firstFewPosts = DateTime.fromObject(
      { year: 2006, month: 10, day: 10 },
      { zone: FixedOffsetZone.utcInstance },
    );
    for await (const { item } of crawlHn({
      nextId: 0,
      stopOnItemWithinDurationMs: -firstFewPosts.diffNow().as("milliseconds"),
    })) {
      const { post, comment } = itemToPostOrComment(item);
      mapExists(post, (p) => posts.push(p));
      mapExists(comment, (c) => comments.push(c));
    }
    expect(posts).toEqual([
      {
        id: 1,
        author: "pg",
        children: [15, 234509, 487171, 82729],
        dead: false,
        deleted: false,
        score: 57,
        textHtml: "",
        timestamp: new Date("2006-10-09T18:21:51.000Z"),
        titleHtml: "Y Combinator",
        url: "http://ycombinator.com",
      },
      {
        id: 2,
        author: "phyllis",
        children: [],
        dead: false,
        deleted: false,
        score: 16,
        textHtml: "",
        timestamp: new Date("2006-10-09T18:30:28.000Z"),
        titleHtml: "A Student's Guide to Startups",
        url: "http://www.paulgraham.com/mit.html",
      },
      {
        id: 3,
        author: "phyllis",
        children: [531602],
        dead: false,
        deleted: false,
        score: 7,
        textHtml: "",
        timestamp: new Date("2006-10-09T18:40:33.000Z"),
        titleHtml: "Woz Interview: the early days of Apple",
        url: "http://www.foundersatwork.com/stevewozniak.html",
      },
      {
        id: 4,
        author: "onebeerdave",
        children: [],
        dead: false,
        deleted: false,
        score: 5,
        textHtml: "",
        timestamp: new Date("2006-10-09T18:47:42.000Z"),
        titleHtml: "NYC Developer Dilemma",
        url: "http://avc.blogs.com/a_vc/2006/10/the_nyc_develop.html",
      },
      {
        id: 5,
        author: "perler",
        children: [],
        dead: false,
        deleted: false,
        score: 7,
        textHtml: "",
        timestamp: new Date("2006-10-09T18:51:04.000Z"),
        titleHtml:
          "Google, YouTube acquisition announcement could come tonight",
        url: "http://www.techcrunch.com/2006/10/09/google-youtube-sign-more-separate-deals/",
      },
      {
        id: 6,
        author: "perler",
        children: [],
        dead: false,
        deleted: false,
        score: 4,
        textHtml: "",
        timestamp: new Date("2006-10-09T18:56:40.000Z"),
        titleHtml:
          "Business Intelligence the Inkling Way: cool prediction markets software",
        url: "http://360techblog.com/2006/10/02/business-intelligence-the-inkling-way/",
      },
      {
        id: 7,
        author: "phyllis",
        children: [],
        dead: false,
        deleted: false,
        score: 5,
        textHtml: "",
        timestamp: new Date("2006-10-09T19:00:55.000Z"),
        titleHtml: "Sevin Rosen Unfunds - why?",
        url: "http://featured.gigaom.com/2006/10/09/sevin-rosen-unfunds-why/",
      },
      {
        id: 8,
        author: "frobnicate",
        children: [],
        dead: false,
        deleted: false,
        score: 10,
        textHtml: "",
        timestamp: new Date("2006-10-09T19:17:39.000Z"),
        titleHtml: "LikeBetter featured by BBC",
        url: "http://news.bbc.co.uk/2/hi/programmes/click_online/5412216.stm",
      },
      {
        id: 9,
        author: "askjigga",
        children: [],
        dead: false,
        deleted: false,
        score: 4,
        textHtml: "",
        timestamp: new Date("2006-10-09T19:19:02.000Z"),
        titleHtml: "weekendr: social network for the weekend",
        url: "http://www.weekendr.com/",
      },
      {
        id: 10,
        author: "frobnicate",
        children: [],
        dead: false,
        deleted: false,
        score: 3,
        textHtml: "",
        timestamp: new Date("2006-10-09T19:21:14.000Z"),
        titleHtml: "PhotoShow: Broadcast Photos to Cable TV",
        url: "http://www.techcrunch.com/2006/10/09/broadcast-photos-to-cable-tv/",
      },
      {
        id: 11,
        author: "frobnicate",
        children: [],
        dead: false,
        deleted: false,
        score: 5,
        textHtml: "",
        timestamp: new Date("2006-10-09T19:24:44.000Z"),
        titleHtml:
          "Participation Inequality: Encouraging More Users to Contribute",
        url: "http://www.useit.com/alertbox/participation_inequality.html",
      },
      {
        id: 12,
        author: "farmer",
        children: [],
        dead: false,
        deleted: false,
        score: 5,
        textHtml: "",
        timestamp: new Date("2006-10-09T19:28:32.000Z"),
        titleHtml: "Wired: The Desktop is Dead",
        url: "http://wired.com/wired/archive/14.10/cloudware.html",
      },
      {
        id: 13,
        author: "phyllis",
        children: [],
        dead: false,
        deleted: false,
        score: 5,
        textHtml: "",
        timestamp: new Date("2006-10-09T19:36:12.000Z"),
        titleHtml: "The Hardest Lessons for Startups to Learn",
        url: "http://www.paulgraham.com/startuplessons.html",
      },
      {
        id: 14,
        author: "pg",
        children: [],
        dead: false,
        deleted: false,
        score: 4,
        textHtml: "",
        timestamp: new Date("2006-10-09T19:50:20.000Z"),
        titleHtml:
          "Small is Beautiful: Building a Successful Company with Less Capital",
        url: "http://blogs.zdnet.com/BTL/?p=3738",
      },
      {
        id: 16,
        author: "pg",
        children: [],
        dead: false,
        deleted: false,
        score: 11,
        textHtml: "",
        timestamp: new Date("2006-10-09T19:51:43.000Z"),
        titleHtml: "Feld: Question Regarding NDAs",
        url: "http://www.feld.com/blog/archives/001979.html",
      },
      {
        id: 18,
        author: "farmer",
        children: [],
        dead: false,
        deleted: false,
        score: 3,
        textHtml: "",
        timestamp: new Date("2006-10-09T19:55:46.000Z"),
        titleHtml: "Voddler Raises $2.2M For Virtual Cable TV",
        url: "http://www.thealarmclock.com/euro/archives/2006/10/stockholmnfounded_vo.html",
      },
      {
        id: 19,
        author: "pg",
        children: [],
        dead: false,
        deleted: false,
        score: 2,
        textHtml: "",
        timestamp: new Date("2006-10-09T19:59:03.000Z"),
        titleHtml: "Will Silicon Light Illuminate the Future?",
        url: "http://www.technologyreview.com/read_article.aspx?id=17588&ch=energy",
      },
      {
        id: 20,
        author: "pg",
        children: [23],
        dead: false,
        deleted: false,
        score: 8,
        textHtml: "",
        timestamp: new Date("2006-10-09T20:00:38.000Z"),
        titleHtml: "Salaries at VC-backed companies",
        url: "http://avc.blogs.com/a_vc/2006/10/search_by_salar.html",
      },
    ]);
    expect(comments).toEqual([
      {
        id: 15,
        author: "sama",
        children: [17],
        dead: false,
        deleted: false,
        parent: 1,
        score: 0,
        textHtml:
          "&#34;the rising star of venture capital&#34; -unknown VC eating lunch on SHR",
        timestamp: new Date("2006-10-09T19:51:01.000Z"),
      },
      {
        id: 17,
        author: "pg",
        children: [1079],
        dead: false,
        deleted: false,
        parent: 15,
        score: 0,
        textHtml: "Is there anywhere to eat on Sandhill Road?",
        timestamp: new Date("2006-10-09T19:52:45.000Z"),
      },
    ]);
  },
  1000 * 60,
);
